In [2]:
import pandas as pd

In [6]:
movies=pd.read_csv("movies.csv")

In [18]:
movies.shape

(2503, 12)

In [36]:
movies

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview,release_year,profit
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...,2014,5.816067e+08
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es...",2010,6.790306e+08
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...,2012,1.298816e+09
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...,2008,8.195584e+08
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di...",2009,2.686706e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2498,19901,Daybreakers,en,2010-01-06,98,2.000000e+07,5.141719e+07,6.5762,6.285,2223,Released,"In the year 2019, a plague has transformed alm...",2010,3.141719e+07
2505,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Released,Phil and Claire Foster fear that their mild-ma...,1995,-5.619119e+06
2506,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Released,Young teenager Sam Witwicky becomes involved i...,1987,1.646479e+08
2507,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Released,Evil pirate Burger Beard is in search of the f...,2000,5.313726e+08
2508,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,Released,"Jerry, a small-town Minnesota car salesman is ...",2011,4.041893e+07

In [8]:
movies.describe()

,movie_id,runtime,budget,revenue,popularity,vote_average,vote_count
count,2.509000e+03,2509.000000,2.509000e+03,2.509000e+03,2509.000000,2509.000000,2509.000000
mean,1.848254e+05,114.420885,5.863972e+07,2.141241e+08,13.691851,6.941640,6194.598246
std,2.571634e+05,21.412944,6.232276e+07,2.716873e+08,18.096247,0.711199,4963.789824
min,5.000000e+00,45.000000,0.000000e+00,0.000000e+00,0.017000,2.945000,475.000000
25%,4.935000e+03,99.000000,1.450000e+07,4.738629e+07,7.449900,6.437000,3026.000000
50%,3.953800e+04,111.000000,3.800000e+07,1.279000e+08,10.393400,6.949000,4358.000000
75%,3.304590e+05,126.000000,8.250000e+07,2.713333e+08,14.863900,7.448000,7261.000000
max,1.368170e+06,242.000000,6.588000e+08,2.923706e+09,438.475700,8.727000,40566.000000

In [11]:
movies.isnull().sum()

movie_id             0
title                0
original_language    0
release_date         0
runtime              0
budget               0
revenue              0
popularity           0
vote_average         0
vote_count           0
status               0
overview             0
dtype: int64

In [12]:
movies.isnull().sum().sum()

np.int64(0)

In [13]:
movies.duplicated().sum()

np.int64(6)

In [14]:
movies[movies.duplicated()]

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
2499,329833,Zoolander 2,en,2016-02-06,100,50000000.0,56722693.0,6.4048,4.927,2411,Released,Derek and Hansel are modelling again when an o...
2500,484641,Anna,en,2019-06-19,119,34000000.0,31626978.0,9.9585,6.719,3043,Released,Beneath Anna Poliatova's striking beauty lies ...
2501,414,Batman Forever,en,1995-06-16,121,100000000.0,336529144.0,10.8455,5.459,5660,Released,Batman faces off against two foes: the schizop...
2502,8814,Doom,en,2005-10-20,105,60000000.0,58100000.0,6.3758,5.202,2493,Released,A team of space marines known as the Rapid Res...
2503,72570,The Vow,en,2012-02-05,104,30000000.0,196114570.0,9.7433,7.225,4287,Released,"Happy young married couple Paige and Leo are, ..."
2504,98,Gladiator,en,2000-05-04,155,103000000.0,465516248.0,38.9610,8.230,21184,Released,"After the death of Emperor Marcus Aurelius, hi..."

In [15]:
movies.columns[movies.columns.duplicated()]

Index([], dtype='object')

In [17]:
movies = movies.drop_duplicates()
movies.shape

(2503, 12)

In [19]:
movies.duplicated().sum()

np.int64(0)

In [21]:
movies.dtypes
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2503 entries, 0 to 2508
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           2503 non-null   int64
 1   title              2503 non-null   object
 2   original_language  2503 non-null   object
 3   release_date       2503 non-null   object
 4   runtime            2503 non-null   int64
 5   budget             2503 non-null   float64
 6   revenue            2503 non-null   float64
 7   popularity         2503 non-null   float64
 8   vote_average       2503 non-null   float64
 9   vote_count         2503 non-null   int64
 10  status             2503 non-null   object
 11  overview           2503 non-null   object
dtypes: float64(4), int64(3), object(5)
memory usage: 254.2+ KB

In [23]:
movies["release_date"] = pd.to_datetime(movies["release_date"])
movies.dtypes

movie_id                      int64
title                        object
original_language            object
release_date         datetime64[ns]
runtime                       int64
budget                      float64
revenue                     float64
popularity                  float64
vote_average                float64
vote_count                    int64
status                       object
overview                     object
dtype: object

In [35]:


movies["release_year"] = movies["release_date"].dt.year
movies["release_year"].head()
movies.info()
movies["release_year"].isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 2503 entries, 0 to 2508
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           2503 non-null   int64
 1   title              2503 non-null   object
 2   original_language  2503 non-null   object
 3   release_date       2503 non-null   datetime64[ns]
 4   runtime            2503 non-null   int64
 5   budget             2503 non-null   float64
 6   revenue            2503 non-null   float64
 7   popularity         2503 non-null   float64
 8   vote_average       2503 non-null   float64
 9   vote_count         2503 non-null   int64
 10  status             2503 non-null   object
 11  overview           2503 non-null   object
 12  release_year       2503 non-null   int32
 13  profit             2503 non-null   float64
dtypes: datetime64[ns](1), float64(5), int32(1), int64(3), object(4)
memory usage: 283.5+ KB

np.int64(0)

In [49]:
movies["profit"] = movies["revenue"] - movies["budget"]
movies["profit"].head()
movies.info()
movies["profit"].isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2503 entries, 0 to 2502
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           2503 non-null   int64
 1   title              2503 non-null   object
 2   original_language  2503 non-null   object
 3   release_date       2503 non-null   object
 4   runtime            2503 non-null   int64
 5   budget             2503 non-null   float64
 6   revenue            2503 non-null   float64
 7   popularity         2503 non-null   float64
 8   vote_average       2503 non-null   float64
 9   vote_count         2503 non-null   int64
 10  status             2503 non-null   object
 11  overview           2503 non-null   object
 12  release_year       2503 non-null   int64
 13  profit             2503 non-null   float64
dtypes: float64(5), int64(4), object(5)
memory usage: 273.9+ KB

np.int64(0)

In [37]:
movies

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview,release_year,profit
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...,2014,5.816067e+08
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es...",2010,6.790306e+08
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...,2012,1.298816e+09
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...,2008,8.195584e+08
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di...",2009,2.686706e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2498,19901,Daybreakers,en,2010-01-06,98,2.000000e+07,5.141719e+07,6.5762,6.285,2223,Released,"In the year 2019, a plague has transformed alm...",2010,3.141719e+07
2505,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Released,Phil and Claire Foster fear that their mild-ma...,1995,-5.619119e+06
2506,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Released,Young teenager Sam Witwicky becomes involved i...,1987,1.646479e+08
2507,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Released,Evil pirate Burger Beard is in search of the f...,2000,5.313726e+08
2508,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,Released,"Jerry, a small-town Minnesota car salesman is ...",2011,4.041893e+07

In [ ]:
movies.to_csv("movies_cleaned.csv", index=False)
import os
print(os.getcwd())

c:\Users\dines\OneDrive\Desktop\guvi project

In [91]:
import pymysql
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:13849#Datasci@localhost/movie_analytics"
)

In [45]:

movies = pd.read_csv("movies_cleaned.csv")
movies

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview,release_year,profit
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...,2014,5.816067e+08
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es...",2010,6.790306e+08
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...,2012,1.298816e+09
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...,2008,8.195584e+08
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di...",2009,2.686706e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2498,19901,Daybreakers,en,2010-01-06,98,2.000000e+07,5.141719e+07,6.5762,6.285,2223,Released,"In the year 2019, a plague has transformed alm...",2010,3.141719e+07
2499,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Released,Phil and Claire Foster fear that their mild-ma...,1995,-5.619119e+06
2500,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Released,Young teenager Sam Witwicky becomes involved i...,1987,1.646479e+08
2501,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Released,Evil pirate Burger Beard is in search of the f...,2000,5.313726e+08
2502,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,Released,"Jerry, a small-town Minnesota car salesman is ...",2011,4.041893e+07

In [46]:
movies.to_sql('movies',if_exists='replace',con=engine)

2503

#CAST

In [68]:
import pandas as pd
cast=pd.read_csv("cast.csv")
cast

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4
...,...,...,...,...,...,...
24912,17699,58224,9048,Clark Gregg,Nat Jones,5
24913,20628,239571,61011,Clarke Peters,Morgan Dupree,6
24914,12827,1948,39391,Edi Gathegi,Haitian Cabbie,7
24915,17362,10494,84509,Yosuke Akimoto,Tejima (voice),6
24916,517,105,1067,Marc McClure,Dave McFly,6

In [69]:
cast.describe()

        cast_row_id      movie_id     person_id    cast_order
count  24917.000000  2.491700e+04  2.491700e+04  24917.000000
mean   12451.382430  1.825776e+05  3.012260e+05      4.489666
std     7189.068289  2.527155e+05  6.589391e+05      2.870028
min        1.000000  5.000000e+00  2.000000e+00      0.000000
25%     6225.000000  4.922000e+03  6.384000e+03      2.000000
50%    12452.000000  3.945100e+04  2.159500e+04      4.000000
75%    18677.000000  3.298330e+05  1.089160e+05      7.000000
max    24902.000000  1.368166e+06  6.340224e+06      9.000000

In [81]:
cast.isnull().sum().sum()
cast = cast.dropna()
cast.isna().sum()

cast_row_id       0
movie_id          0
person_id         0
actor_name        0
character_name    0
cast_order        0
dtype: int64

In [77]:
cast.dtypes

cast_row_id        int64
movie_id           int64
person_id          int64
actor_name        object
character_name    object
cast_order         int64
dtype: object

In [78]:
cast.duplicated().sum()

np.int64(0)

In [79]:
cast = cast.drop_duplicates()
cast.duplicated().sum()

np.int64(0)

In [83]:
cast.apply(pd.Series.duplicated).sum()

cast_row_id           0
movie_id          22394
person_id         13601
actor_name        13610
character_name     5418
cast_order        24881
dtype: int64

In [84]:
cast['cast_row_id'].is_unique

True

In [85]:
cast.duplicated(subset=['movie_id', 'person_id']).sum()

np.int64(0)

In [103]:
cast

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4
...,...,...,...,...,...,...
24886,24898,19901,77496,Vince Colosimo,Christopher Caruso,5
24887,24899,19901,33182,Jay Laga'aia,Senator Turner,6
24888,24900,19901,76068,Michael Dorman,Frankie Dalton,7
24889,24901,19901,1121519,Harriet Minto-Day,Lisa Barrett,8
24890,24902,19901,61911,Tiffany Lamb,News Reader,9

In [ ]:
cast.to_csv("cast_cleaned.csv", index=False)
cast

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4
...,...,...,...,...,...,...
24886,24898,19901,77496,Vince Colosimo,Christopher Caruso,5
24887,24899,19901,33182,Jay Laga'aia,Senator Turner,6
24888,24900,19901,76068,Michael Dorman,Frankie Dalton,7
24889,24901,19901,1121519,Harriet Minto-Day,Lisa Barrett,8
24890,24902,19901,61911,Tiffany Lamb,News Reader,9

In [105]:
import pymysql
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:13849#Datasci@localhost/movie_analytics"
)

In [106]:
cast = pd.read_csv("cast_cleaned.csv")
cast

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4
...,...,...,...,...,...,...
24886,24898,19901,77496,Vince Colosimo,Christopher Caruso,5
24887,24899,19901,33182,Jay Laga'aia,Senator Turner,6
24888,24900,19901,76068,Michael Dorman,Frankie Dalton,7
24889,24901,19901,1121519,Harriet Minto-Day,Lisa Barrett,8
24890,24902,19901,61911,Tiffany Lamb,News Reader,9

In [107]:
cast.to_sql('cast',if_exists='replace',con=engine)

24891

#CREW

In [41]:
crew=pd.read_csv("crew.csv")
crew

,crew_row_id,movie_id,person_id,person_name,job,department
0,1,157336,527,Jonathan Nolan,Writer,Writing
1,2,157336,525,Christopher Nolan,Writer,Writing
2,3,157336,525,Christopher Nolan,Director,Directing
3,4,27205,525,Christopher Nolan,Writer,Writing
4,5,27205,525,Christopher Nolan,Director,Directing
...,...,...,...,...,...,...
7292,1026,566525,57264,David Callaham,Screenplay,Writing
7293,1243,76492,53684,Robert Smigel,Screenplay,Writing
7294,5532,9352,57407,David Mandel,Writer,Writing
7295,5235,58224,89027,Jared Stern,Screenplay,Writing
7296,264,808,12083,Joe Stillman,Writer,Writing

In [43]:
crew.shape

(7297, 6)

In [44]:
crew.describe()

       crew_row_id      movie_id     person_id
count  7297.000000  7.297000e+03  7.297000e+03
mean   3643.692339  1.770601e+05  2.366333e+05
std    2104.641104  2.466716e+05  5.204678e+05
min       1.000000  5.000000e+00  1.000000e+00
25%    1820.000000  5.255000e+03  7.394000e+03
50%    3644.000000  3.840800e+04  2.640600e+04
75%    5466.000000  3.181210e+05  8.219400e+04
max    7289.000000  1.368166e+06  6.085456e+06

In [47]:
crew.isnull().sum().sum()

np.int64(0)

In [50]:
crew.isnull().sum()

crew_row_id    0
movie_id       0
person_id      0
person_name    0
job            0
department     0
dtype: int64

In [52]:
crew.dtypes

crew_row_id     int64
movie_id        int64
person_id       int64
person_name    object
job            object
department     object
dtype: object

In [55]:
crew.isna()
crew.isna().sum()
crew.isna().sum().sum()

np.int64(0)

In [64]:
crew.duplicated().sum()
crew[crew.duplicated()]
crew = crew.drop_duplicates()

In [75]:
crew['crew_row_id'].duplicated().sum()

np.int64(0)

In [79]:
crew['crew_members_per_movie'] = (
    crew.groupby('movie_id')['person_id'].transform('nunique')
)

In [83]:
crew.shape

(7289, 7)

In [84]:
crew.to_csv("crew_cleaned.csv", index=False)

In [104]:
import pymysql
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:13849#Datasci@localhost/movie_analytics"
)

In [89]:
crew = pd.read_csv("crew_cleaned.csv")
crew.to_sql('crew',if_exists='replace',con=engine)

7289

#GENRES

In [91]:
genres=pd.read_csv("genres.csv")

In [92]:
genres

    genre_id       genre_name
0         28           Action
1         12        Adventure
2         16        Animation
3         35           Comedy
4         80            Crime
5         99      Documentary
6         18            Drama
7      10751           Family
8         14          Fantasy
9         36          History
10        27           Horror
11     10402            Music
12      9648          Mystery
13     10749          Romance
14       878  Science Fiction
15     10770         TV Movie
16        53         Thriller
17     10752              War
18        37          Western

In [95]:
genres.dtypes

genre_id       int64
genre_name    object
dtype: object

In [ ]:
genres.isnull().sum()

genre_id      0
genre_name    0
dtype: int64

In [98]:
genres.duplicated().sum()

np.int64(0)

In [99]:
genres['genre_id'].duplicated().sum()

np.int64(0)

In [101]:
genres['genre_name_length'] = genres['genre_name'].str.len()
genres

    genre_id       genre_name  genre_name_length
0         28           Action                  6
1         12        Adventure                  9
2         16        Animation                  9
3         35           Comedy                  6
4         80            Crime                  5
5         99      Documentary                 11
6         18            Drama                  5
7      10751           Family                  6
8         14          Fantasy                  7
9         36          History                  7
10        27           Horror                  6
11     10402            Music                  5
12      9648          Mystery                  7
13     10749          Romance                  7
14       878  Science Fiction                 15
15     10770         TV Movie                  8
16        53         Thriller                  8
17     10752              War                  3
18        37          Western                  7

In [102]:
genres.to_csv("genres_cleaned.csv", index=False)

In [105]:
genres= pd.read_csv("genres_cleaned.csv")
genres.to_sql('genres',if_exists='replace',con=engine)

19

# MOVIE GENRES

In [107]:
movie_genres=pd.read_csv("movie_genres.csv")
movie_genres

      movie_id  genre_id
0       157336        12
1       157336        18
2       157336       878
3        27205        28
4        27205       878
...        ...       ...
6883      9705        53
6884      8914        28
6885      1429        80
6886     57800     10751
6887    456740        27

[6888 rows x 2 columns]

In [108]:
movie_genres.dtypes

movie_id    int64
genre_id    int64
dtype: object

In [109]:
movie_genres.isnull().sum().sum()

np.int64(0)

In [111]:
movie_genres.duplicated().sum()
movie_genres = movie_genres.drop_duplicates()

In [120]:
movie_genres['genre_count'] = (
    movie_genres.groupby('movie_id')['genre_id'].transform('nunique')
)

C:\Users\dines\AppData\Local\Temp\ipykernel_24608\3808658970.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_genres['genre_count'] = (

In [121]:
movie_genres

      movie_id  genre_id  genre_count
0       157336        12            3
1       157336        18            3
2       157336       878            3
3        27205        28            3
4        27205       878            3
...        ...       ...          ...
6873      7461        53            4
6874      7461        80            4
6875     19901        28            3
6876     19901        14            3
6877     19901       878            3

[6878 rows x 3 columns]

In [122]:
movie_genres.to_csv("movie_genres_cleaned.csv", index=False)

In [ ]:
movie_genres= pd.read_csv("movie_genres_cleaned.csv")
movie_genres.to_sql('movie_genres',if_exists='replace',con=engine)

6878

# MOVIE_KEYWORDS

In [125]:
movie_keywords=pd.read_csv("movie_keywords.csv")
movie_keywords

       movie_id  keyword_id                    keyword_name
0        157336        1612                      spacecraft
1        157336        4776               race against time
2        157336         310  artificial intelligence (a.i.)
3        157336        1432                            nasa
4        157336        1521                       time warp
...         ...         ...                             ...
41696      1271      329753                     epic heroes
41697     10483         378                          prison
41698       111         701                            cuba
41699    339397       10048                 unrequited love
41700      7446      167477                       land mine

[41701 rows x 3 columns]

In [127]:
movie_keywords.dtypes

movie_id         int64
keyword_id       int64
keyword_name    object
dtype: object

In [128]:
movie_keywords.isnull().sum().sum()

np.int64(0)

In [133]:
movie_keywords.duplicated().sum()

np.int64(0)

In [131]:
movie_keywords = movie_keywords.drop_duplicates()

In [134]:
movie_keywords.duplicated(
    subset=['movie_id', 'keyword_id']
).sum()

np.int64(0)

In [135]:
movie_keywords['keyword_count'] = (
    movie_keywords.groupby('movie_id')['keyword_id']
    .transform('nunique')
)

C:\Users\dines\AppData\Local\Temp\ipykernel_24608\2171242008.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_keywords['keyword_count'] = (

In [137]:
movie_keywords.to_csv("movie_keywords_cleaned.csv", index=False)

In [138]:
movie_keywords= pd.read_csv("movie_keywords_cleaned.csv")
movie_keywords.to_sql('movie_keywords',if_exists='replace',con=engine)

41681